stages:
    - build

build-ubuntu:
    image: registry.videolan.org:5000/libplacebo-ubuntu-cosmic:20181204200145
    stage: build
    tags:
        - debian
        - amd64
    script:
        - gcovr --version
